package com.golem.boxy.loader;

import net.fabricmc.tinyremapper.IMappingProvider;

import java.util.HashMap;
import java.util.Map;

/**
 * Converts Voxy's {@code voxy.accesswidener} (Fabric, intermediary-named) into a Forge 1.20.1
 * {@code META-INF/accesstransformer.cfg} (official dotted classes + SRG members). Foxy applied the
 * widener as a live NeoForge class processor because NeoForge runs in official names; Forge runs in
 * SRG, so Boxy instead emits a real access-transformer that Forge applies natively.
 *
 * <p>The SRG names come from the same {@link BoxyMappings} provider used for the bytecode remap, so
 * the AT and the remapped classes stay in lockstep.
 */
final class AccessWidenerToAt {
    private AccessWidenerToAt() {}

    static String convert(String awText, IMappingProvider provider) {
        Lookup lk = Lookup.from(provider);
        StringBuilder out = new StringBuilder();
        out.append("# Generated by Boxy from voxy.accesswidener\n");

        boolean header = true;
        for (String raw : awText.split("\n")) {
            String line = raw;
            int hash = line.indexOf('#');
            if (hash >= 0) line = line.substring(0, hash);
            line = line.strip();
            if (line.isEmpty()) continue;
            if (header) { header = false; continue; } // "accessWidener v1 intermediary"

            String[] p = line.split("\\s+");
            if (p.length < 3) continue;
            String access = p[0]; // accessible | extendable | mutable
            String type = p[1];   // class | field | method
            boolean removeFinal = access.equals("extendable") || access.equals("mutable");
            String at = removeFinal ? "public-f" : "public";

            switch (type) {
                case "class" -> {
                    String owner = lk.clazz(p[2]);
                    if (owner != null) out.append(at).append(' ').append(dot(owner)).append('\n');
                }
                case "field" -> {
                    if (p.length < 5) continue; // accessible field <owner> <name> <desc>
                    String srg = lk.field(p[2], p[3]);
                    String owner = lk.clazz(p[2]);
                    if (srg != null && owner != null) {
                        out.append(at).append(' ').append(dot(owner)).append(' ').append(srg).append('\n');
                    }
                }
                case "method" -> {
                    if (p.length < 5) continue; // accessible method <owner> <name> <desc>
                    String srg = lk.method(p[2], p[3], p[4]);
                    String owner = lk.clazz(p[2]);
                    if (srg != null && owner != null) {
                        out.append(at).append(' ').append(dot(owner)).append(' ')
                                .append(srg).append(lk.remapDesc(p[4])).append('\n');
                    }
                }
                default -> {}
            }
        }
        return out.toString();
    }

    private static String dot(String internal) {
        return internal.replace('/', '.');
    }

    /** Eagerly collects the intermediary->srg provider into lookup tables. */
    private static final class Lookup implements IMappingProvider.MappingAcceptor {
        final Map<String, String> classes = new HashMap<>();
        final Map<String, String> fields = new HashMap<>();
        final Map<String, String> methods = new HashMap<>();

        static Lookup from(IMappingProvider provider) {
            Lookup l = new Lookup();
            provider.load(l);
            return l;
        }

        String clazz(String intInternal) {
            return classes.get(intInternal);
        }

        String field(String intOwner, String intName) {
            return fields.get(intOwner + "#" + intName);
        }

        String method(String intOwner, String intName, String intDesc) {
            return methods.get(intOwner + "#" + intName + intDesc);
        }

        /** Remap a descriptor's class types intermediary -> official (slashed), for AT method lines. */
        String remapDesc(String desc) {
            StringBuilder sb = new StringBuilder(desc.length());
            int i = 0;
            while (i < desc.length()) {
                char c = desc.charAt(i);
                if (c == 'L') {
                    int end = desc.indexOf(';', i);
                    String t = desc.substring(i + 1, end);
                    sb.append('L').append(classes.getOrDefault(t, t)).append(';');
                    i = end + 1;
                } else {
                    sb.append(c);
                    i++;
                }
            }
            return sb.toString();
        }

        @Override public void acceptClass(String srcName, String dstName) { classes.put(srcName, dstName); }
        @Override public void acceptField(IMappingProvider.Member field, String dstName) { fields.put(field.owner + "#" + field.name, dstName); }
        @Override public void acceptMethod(IMappingProvider.Member method, String dstName) { methods.put(method.owner + "#" + method.name + method.desc, dstName); }
        @Override public void acceptMethodArg(IMappingProvider.Member method, int lvIndex, String dstName) {}
        @Override public void acceptMethodVar(IMappingProvider.Member method, int lvIndex, int startOpIdx, int asmIndex, String dstName) {}
    }
}
