modLoader="javafml"
loaderVersion="[4,)"
license="GPL-3.0-only"

[[mods]]
modId="boxy"
version="${mod_version}"
displayName="Boxy"
authors="golem"
description='''Server LOD streaming and distant entity rendering for native Voxy on NeoForge 1.21.1.'''

[[dependencies.boxy]]
modId="neoforge"
type="required"
versionRange="[21.1.248,)"
ordering="NONE"
side="BOTH"

[[dependencies.boxy]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.boxy]]
modId="voxy"
type="required"
versionRange="[0.2.15-beta]"
ordering="AFTER"
side="CLIENT"

[[dependencies.boxy]]
modId="sodium"
type="optional"
versionRange="[0.8.12-beta.2,0.9)"
ordering="AFTER"
side="CLIENT"

[[mixins]]
config="boxy.mixins.json"

[[dependencies.boxy]]
modId="iris"
type="optional"
versionRange="[1.8.14-beta.1,)"
ordering="AFTER"
side="CLIENT"
